language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby-18mode
  - jruby-19mode
  - rbx

bundler_args: --without development

script:
  - bundle exec rspec
  - bundle exec ruby integration/contracts.rb
  - bundle exec ruby integration/contracts_pattern_matching.rb
